Repository dotnet/docs, pull requests merged in 2018-02, with the labels that each got.

#4360 fix "te" to "the"
  samples/snippets/csharp/VS_Snippets_Remoting/System.Net.Sockets.Socket/CS/socket.cs
Labels: *1st-time docs contributor!*

#4362 Fix quoted XML identifiers in cref
  docs/csharp/programming-guide/xmldoc/xml-documentation-comments.md
Labels: *1st-time docs contributor!*

#4371 Use monospace for the whole method signature
  docs/standard/design-guidelines/dispose-pattern.md
Labels: verify-build-before-merge

#2961 fixing formatting issues
  docs/csharp/language-reference/preprocessor-directives/preprocessor-if.md
Labels: verify-build-before-merge

#3261 adding StackFrameExtensions apis
  add/metadata/System.Diagnostics/StackFrameExtensions.meta.md
  xml/System.Diagnostics/StackFrameExtensions.xml
Labels: Area - API Reference, verify-build-before-merge, waiting-on-reviews

#4340 Correct variable naming in code sample
  docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/nosql-database-persistence-infrastructure.md
Labels: *1st-time docs contributor!*

#4397 Updated install instruction for .NET Core 2.x on Ubuntu to latest SDK
  docs/core/linux-prerequisites.md
Labels: *1st-time docs contributor!*

#4402 Typo in docs/core/tools/index.md
  docs/core/tools/index.md
Labels: *1st-time docs contributor!*, verify-build-before-merge

#4317 fix indentation/remove framework
  xml/System.Threading/Timer.xml
  xml/System.Timers/Timer.xml
Labels: Area - API Reference

#4403 Update button-styles-and-templates.md
  docs/framework/wpf/controls/button-styles-and-templates.md
Labels: *1st-time docs contributor!*

#4369 fixed race condition in C# event keyword doc
  docs/csharp/language-reference/keywords/codesnippet/CSharp/event_1.cs
Labels: verify-build-before-merge

#4414 Fix type of (+@) operator example
  docs/fsharp/language-reference/generics/statically-resolved-type-parameters.md
Labels: *1st-time docs contributor!*

#4389 Updated for VB What's New for 15.3, 15.5
  docs/visual-basic/getting-started/whats-new.md
Labels: verify-build-before-merge

#4387 Revised generics topic to make it implementation-independent
  docs/standard/generics/collections.md
  docs/standard/generics/toc.md
Labels: verify-build-before-merge

#2860 updated for csproj/net 2.0
  docs/core/porting/third-party-deps.md
Labels: waiting-on-reviews

#4416 Duplication in control-styles-and-templates.md
  docs/framework/wpf/controls/control-styles-and-templates.md
Labels: verify-build-before-merge

#4385 added note about sdk 2.1
  docs/core/versions/index.md
Labels: Area - .NET Core Guide

#4380 Fix broken link (Dockerfile on Windows Containers)
  docs/core/docker/intro-net-docker.md
Labels: *1st-time docs contributor!*

#4425 Update service-identity-and-authentication.md
  docs/framework/wcf/feature-details/service-identity-and-authentication.md
Labels: verify-build-before-merge

#4424 Update configuring-timeout-values-on-a-binding.md
  docs/framework/wcf/feature-details/configuring-timeout-values-on-a-binding.md
Labels: *1st-time docs contributor!*

#4232 Consolidated XAML fragments
  docs/framework/wpf/data/binding-declarations-overview.md
  docs/framework/wpf/data/how-to-control-when-the-textbox-text-updates-the-source.md
  docs/framework/wpf/data/how-to-create-a-simple-binding.md
  docs/framework/wpf/data/how-to-make-data-available-for-binding-in-xaml.md
  samples/snippets/csharp/VS_Snippets_Wpf/BindConversion/CSharp/Window1.xaml.cs
  samples/snippets/csharp/VS_Snippets_Wpf/SimpleBinding/CSharp/Page1.xaml
  samples/snippets/visualbasic/VS_Snippets_Wpf/BindConversion/visualbasic/window1.xaml.vb
  samples/snippets/visualbasic/VS_Snippets_Wpf/SimpleBinding/VisualBasic/Page1.xaml
  xml/System.Windows.Data/Binding.xml
  xml/System.Windows.Data/ObjectDataProvider.xml
Labels: verify-build-before-merge

#4426 Grammar fixes link texts
  docs/framework/wpf/controls/control-styles-and-templates.md
Labels: verify-build-before-merge

#3339 F3 shortcut key support in WinForms DataGridView
  docs/framework/winforms/controls/default-keyboard-and-mouse-handling-in-the-windows-forms-datagridview-control.md
  docs/framework/winforms/controls/sorting-data-in-the-windows-forms-datagridview-control.md
  xml/System.Windows.Forms/DataGridViewColumnSortMode.xml
Labels: *1st-time docs contributor!*, verify-build-before-merge

#4438 Update decimal.md
  docs/csharp/language-reference/keywords/decimal.md
Labels: *1st-time docs contributor!*

#4446 Remove unused variable creating confusion.
  samples/snippets/visualbasic/VS_Snippets_Wpf/LayoutInformation/VisualBasic/Window1.xaml.vb
Labels: *1st-time docs contributor!*

#4442 Fix grammar in docs: communication-in-microservice-architecture.md
  docs/standard/microservices-architecture/architect-microservice-container-applications/communication-in-microservice-architecture.md
Labels: *1st-time docs contributor!*

#4449 add two options explanation
  docs/visual-basic/reference/command-line-compiler/index.md
Labels: Area - Visual Basic Guide, verify-build-before-merge

#3615 Maximum size of file to be compressed
  xml/System.IO.Compression/ZipFileExtensions.xml
Labels: *1st-time docs contributor!*

#4436 Remove unused variable
  samples/snippets/csharp/VS_Snippets_Wpf/LayoutInformation/CSharp/Window1.xaml.cs
Labels: *1st-time docs contributor!*

#4444 Addressed customer feedback about ControlBox property
  xml/System.Windows.Forms/Form.xml
Labels: verify-build-before-merge

#4434 Fixed example Snippet and clarified it.
  docs/csharp/local-functions-vs-lambdas.md
Labels: *1st-time docs contributor!*

#4432 fix broken links and review topic
  docs/visual-basic/getting-started/additional-resources.md
Labels: Area - Visual Basic Guide, verify-build-before-merge

#4445 replace wrong example
  xml/System.Security.Cryptography/DES.xml
Labels: verify-build-before-merge

#4430 fix broken links
  docs/standard/analyzers/portability-analyzer.md
Labels: waiting-on-reviews

#4422 fix broken links
  docs/core/docker/intro-net-docker.md
Labels: waiting-on-reviews

#4459 Replaced fwlinks in csharp\programming-guide folder
  docs/csharp/programming-guide/delegates/index.md
  docs/csharp/programming-guide/events/index.md
  docs/csharp/programming-guide/exceptions/index.md
  docs/csharp/programming-guide/file-system/how-to-iterate-through-a-directory-tree.md
  docs/csharp/programming-guide/inside-a-program/coding-conventions.md
  docs/csharp/programming-guide/nullable-types/index.md
Labels: verify-build-before-merge

#4464 Update namespaces.md
  docs/fsharp/language-reference/namespaces.md
Labels: verify-build-before-merge

#4463 Update modules.md
  docs/fsharp/language-reference/modules.md
Labels: verify-build-before-merge

#4472 Use centimeters instead of inches
  docs/csharp/quick-starts/numbers-in-csharp-local.md
  docs/csharp/quick-starts/numbers-in-csharp.yml
Labels: verify-build-before-merge

#4475 Update type_getinterface.cs
  samples/snippets/csharp/VS_Snippets_CLR/Type_GetInterface/CS/type_getinterface.cs
Labels: *1st-time docs contributor!*

#4478 Update docs about Regular Expressions
  docs/standard/base-types/anchors-in-regular-expressions.md
  docs/standard/base-types/best-practices.md
  docs/standard/base-types/details-of-regular-expression-behavior.md
  docs/standard/base-types/grouping-constructs-in-regular-expressions.md
  docs/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format.md
  docs/standard/base-types/quantifiers-in-regular-expressions.md
  docs/standard/base-types/regular-expression-example-scanning-for-hrefs.md
  samples/snippets/csharp/VS_Snippets_CLR/RegularExpressions.Examples.Email/cs/example4.cs
  samples/snippets/csharp/VS_Snippets_CLR/conceptual.regex/cs/example2.cs
  samples/snippets/visualbasic/VS_Snippets_CLR/RegularExpressions.Examples.Email/vb/example4.vb
  samples/snippets/visualbasic/VS_Snippets_CLR/conceptual.regex/vb/example2.vb
Labels: *1st-time docs contributor!*

#4482 Fixed Typo
  docs/standard/parallel-programming/introduction-to-plinq.md
Labels: *1st-time docs contributor!*

#4431 Fixes #4350 - Clarify System.Uri constructor overload should have trailing slash
  xml/System/Uri.xml
Labels: *1st-time docs contributor!*

#4467 How to parse strings: made code snippets consistent
  docs/csharp/how-to/parse-strings-using-split.md
  samples/snippets/csharp/how-to/strings/ParseStringsUsingSplit.cs
Labels: verify-build-before-merge

#4488 Main function access modifier fixed
  docs/csharp/tutorials/console-webapiclient.md
Labels: *1st-time docs contributor!*

#4289 Create get started with syntax analysis
  docs/csharp/roslyn-sdk/get-started/media/walkthrough-csharp-syntax-figure1.png
  docs/csharp/roslyn-sdk/get-started/syntax-analysis.md
  docs/csharp/roslyn-sdk/toc.md
  samples/csharp/PatternMatching/PatternMatching.csproj
  samples/csharp/roslyn-sdk/SyntaxQuickStart/HelloSyntaxTree/HelloSyntaxTree.csproj
  samples/csharp/roslyn-sdk/SyntaxQuickStart/HelloSyntaxTree/Program.cs
  samples/csharp/roslyn-sdk/SyntaxQuickStart/SyntaxQuickStart.sln
  samples/csharp/roslyn-sdk/SyntaxQuickStart/SyntaxWalker/Program.cs
  samples/csharp/roslyn-sdk/SyntaxQuickStart/SyntaxWalker/SyntaxWalker.csproj
  samples/csharp/roslyn-sdk/SyntaxQuickStart/SyntaxWalker/UsingCollector.cs
Labels: verify-build-before-merge

#4331 Get started with semantic analysis
  docs/csharp/roslyn-sdk/get-started/semantic-analysis.md
  docs/csharp/roslyn-sdk/toc.md
  samples/csharp/roslyn-sdk/SemanticQuickStart/SemanticQuickStart/Program.cs
  samples/csharp/roslyn-sdk/SemanticQuickStart/SemanticQuickStart/SemanticQuickStart.csproj
  samples/csharp/roslyn-sdk/SemanticQuickStart/SemanticQuickStart/SemanticQuickStart.sln
Labels: verify-build-before-merge

#4100 Document Roslyn Diagnostics Security Analyzer
  docs/standard/analyzers/framework-analyzer.md
  docs/standard/analyzers/index.md
  docs/standard/analyzers/media/framework-analyzers-1.png
  docs/standard/analyzers/media/framework-analyzers-2.png
  docs/toc.md
Labels: verify-build-before-merge

#4501 Update source.vb
  samples/snippets/visualbasic/VS_Snippets_Winforms/Classic CheckedListBox Example/VB/source.vb
Labels: * contributor! *

#4497 Update ref.md
  docs/csharp/language-reference/keywords/ref.md
Labels: * contributor! *

#4499 replaced image + checked lists + formatting
  images/alerts.png
  styleguide/template.md
Labels: verify-build-before-merge

#4496 Removed broken and outdated link
  docs/framework/configure-apps/file-schema/compiler/compiler-element.md
Labels: verify-build-before-merge
